atlantis:
  version: 0.19.7
tg_atlantis_config:
  version: 1.20.0
terraform:
  version: 1.5.5 # TF 1.5.5 was the last change before the BSL license change
terragrunt:
  version: 0.91.4
kubectl:
  version: 1.31.2
helm:
  version: 3.16.2
